export const CONFIG = {
  WORD_LIMIT_PER_ENTRY: 3000,
  AUTOSAVE_DEBOUNCE_MS: 800,
  SESSION_EXPIRY_DAYS: 30,
  PASSWORD_MIN_LENGTH: 8,
  DEVICE_ID_MIN_LENGTH: 12,
  SESSION_TOKEN_MIN_LENGTH: 10,
  DB_CONNECTION_POOL: {
    MAX_CONNECTIONS: 10,
    IDLE_TIMEOUT_SECONDS: 20,
    MAX_LIFETIME_SECONDS: 60 * 30,
    CONNECT_TIMEOUT_SECONDS: 10,
  },
} as const
